### ISSUE TITLE
X & Y Gradient not working

### ISSUE THREAD

**Issue by DevChuckNorris** [JTippetts/accidental-noise-library#3]
With a simple x or y gradient the output looks like this:
[Y Gradient](http://puu.sh/nBNOH/ada5fd82d7.png)
[X Gradient](http://puu.sh/nBNTK/435656db72.png)

The code is:
```c
    anl::CKernel kernel;
    anl::CNoiseExecutor vm(kernel);
    auto b = kernel.x();
    anl::CArray2Drgba img(512, 512);

    anl::mapRGBA2D(anl::SEAMLESS_NONE, img, kernel, anl::SMappingRanges(), 0, b);
    anl::saveRGBAArray("img.png", &img);
```

**Comment by JTippetts** [comment]
It is working as intended. x() and y() simply return the x or y component of the input coordinate. Since SMappingRanges() defaults to mapping the area (-1,-1)->(1,1), when x or y is less than 0, it returns a negative value. When saving an RGBA image, the image saving code multiplies the color channels by 256, then casts them to unsigned char. When done with a negative number, this has the discontinuity effect you see in your example.

If you wish to not have the discontinuity at x==0, change your call to the SMappingRanges constructor to SMappingRanges(0,1,0,1)
