### ISSUE TITLE
How to make fbm with cellular noise?

### ISSUE THREAD

**Issue by axtrend** [JTippetts/accidental-noise-library#4]
It seems that cellular noise need other treatment than perlin, value and simplex. But none of this is explained.
I tried to make cellular noise with fbm functions but they output gradient (perlin?) noise. This is a little confusing. 
Code:

```
switch(basistype)
    {
    case anl::OP_ValueBasis:
        valueBasis(interpindex, seed);
        break;
    case anl::OP_GradientBasis:
        gradientBasis(interpindex, seed);
        break;
    case anl::OP_SimplexBasis:
        simplexBasis(seed);
        break;
    default:
        gradientBasis(interpindex, seed);
        break;
    }
```

**Comment by JTippetts** [comment]
The simple* functions are hacks more than anything, intended to quickly get classic versions of Perlin noise in place quickly. Because the Value/Gradient/Simplex basis functions all have similar usage (supply an interpolation function and a seed and you're set) it's easy to use them interchangeably in the fractal functions. Cellular, however, requires that you supply coefficients for F1,F2,F3 and F4, so they are not easily interchangeable with the other basis functions.

You can, however, build up a fractal "by hand" using cellular noise as the basis.  Simply duplicate the functionality of simpleFractalLayer, substituting cellular noise for the other choice of basis function.

**Comment by axtrend** [comment]
Thanks. Can you explain what are optimal values of these parameters to get something like  [this](http://images.cnitblog.com/blog/359523/201312/31085028-ba179b5149ff4665a22402d61b8f2db5.png) and scale it by frequency?
