### ISSUE TITLE
Cellular noise 3D seamless mode

### ISSUE THREAD

**Issue by axtrend** [JTippetts/accidental-noise-library#5]
It seems that mapping cellular noise with seamless mode produces vertical artifacts.
Code:
```
anl::SMappingRanges ranges;
ranges.mapx0=0.0; ranges.mapy0=0.0; ranges.mapz0=0.0;
ranges.mapx1=10.0; ranges.mapy1=10.0; ranges.mapz1=10.0;
ranges.loopx0=0.0; ranges.loopy0=0.0; ranges.loopz0=0.0;
ranges.loopx1=10.0; ranges.loopy1=10.0; ranges.loopz1=10.0;

glm::ivec3 size = glm::ivec3(64);
anl::CArray3Dd img1(size.x,size.y,size.z);
anl::CArray3Dd img2(size.x,size.y,size.z);
anl::CKernel kernel;
auto b=kernel.cellularBasis(kernel.constant(1.0), kernel.constant(0.0), kernel.constant(0.0), kernel.constant(0.0),
                          kernel.constant(0.0), kernel.constant(0.0), kernel.constant(0.0), kernel.constant(0.0),
                          kernel.constant(0.0), kernel.seed(1234));
anl::map3D(anl::SEAMLESS_XYZ, img1, kernel, ranges, b);
anl::map3D(anl::SEAMLESS_NONE, img2, kernel, ranges, b);
```

http://i65.tinypic.com/qxripf.jpg

This occurs only in 3D.

**Comment by JTippetts** [comment]
How are you generating the images? Are you generating them by writing out one layer in the 3D volume structure?

I have been unable to reproduce the issue using the 2D mapping functions with SEAMLESS_XYZ so i'm wondering if the bug is in the 3D mapping code.

**Comment by axtrend** [comment]
I first populate vector and then init 3D GL_RG16F texture using pointer to data.

```
std::vector<GLfloat> map3D;
    for (int x = 0; x < size.x; ++x)
    {
        for (int y = 0; y < size.y; ++y)
        {
            for (int z = 0; z < size.z; ++z)
            {
                float noise1 = img1.get(x, y, z);
                float noise2 = img2.get(x, y, z);
                map3D.push_back(noise1);
                map3D.push_back(noise2);
            }
        }
    }
```
This images are slices from 3D texture. Left is R component - img1, right is G component - img2.

Yes, in map2D with SEAMLESS_XYZ it is ok.

**Comment by JTippetts** [comment]
Gotta be an issue with the 3D mapping then. Let me dig in and see what I can find. Been awhile since I touched any of that code, might take me a bit.

**Comment by JTippetts** [comment]
Have been unable to reproduce.

![Cell noise](http://i.imgur.com/pz5tMn4.png)

```k=CKernel()

img=CArray2Dd(64,64)
buf=CArray3Dd(64,64,64)

k:cellularBasis(k:constant(1), k:zero(), k:zero(), k:zero(),
 k:zero(), k:zero(), k:zero(), k:zero(), k:constant(0), k:seed(1234))

range=SMappingRanges()
range.mapx0, range.mapy0, range.mapz0=0,0,0
range.mapx1, range.mapy1, range.mapz1=10,10,10
range.loopx0, range.loopy0, range.loopz0=0,0,0
range.loopx1, range.loopy1, range.loopz1=10,10,10

map3D(SEAMLESS_XYZ, buf, k, range, k:lastIndex())

local x,y
for x=0,63,1 do
	for y=0,63,1 do
		local v=buf:get(x,y,0)
		img:set(x,y,v)
	end
end
img:scaleToRange(0,1)
saveDoubleArray("loop.png", img)
```

Are you using the latest from the repo?

**Comment by JTippetts** [comment]
Okay, I have managed to reproduce. Looks like the artifacts happen along the Z axis. Let me investigate further.

**Comment by axtrend** [comment]
When sampling I visualize all slices using vec3(texcoord, z) where z is some uniform incremented in range [0, 1]. Then I can see whole texture. Maybe something with 6D cellular.

**Comment by JTippetts** [comment]
I don't see anything mechanically wrong in the code. My hunch (unless I'm missing something) is that it's due to the cell function, like you say. The cell function only checks points in the neighborhood of one cell out from the cell containing the point being evaluated, and even in non-tiling cases it can often result in discontinuities, given that the nearest point might not actually lie in that neighborhood. The fact that the artifacts seem to align on cell boundaries tentatively confirms this in my mind. The domain distortion introduced by the seamless mapping most likely exacerbates the problem.

Some sources discussing cell noise (including Worley himself) suggest evaluating a neighborhood 2 cells out from the center cell. That is, while currently a 2D cell function iterates a neighborhood 3x3 cells in size to find the 4 nearest points, it should instead iterate a neighborhood 5x5 cells in size. The drawback of using a larger neighborhood, of course, is that computational time is drastically increased. Currently, 6D noise (what is sampled when using SEAMLESS_XYZ) has to test 729 cells to find the nearest points (3^6). If the neighborhood is increased to 2 cells out, that means it will have to test 15,625 (5^6) cells instead for each point evaluated. Already, seamless 6D noise on a 64x64x64 buffer takes my poor machine several minutes to evaluate. Increasing the neighborhood size will make it significantly longer.

I'm thinking that, unless something comes up or I find something I may be missing, I might need to file this one in the CANTFIX box...
